version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: shyn_postgres
    environment:
      POSTGRES_DB: shyn_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: .
    container_name: shyn_auth_service
    ports:
      - "8080:8080"  # порт внутри контейнераf
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shyn_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: shyn_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service


volumes:
  postgres_data: