services:
  postgres:
    image: postgres:15
    container_name: hiking_postgres
    environment:
      POSTGRES_DB: hiking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: .
    container_name: hiking_auth_service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres

volumes:
  postgres_data: