services:
  postgres:
    image: postgres:15
    container_name: shyn_postgres
    environment:
      POSTGRES_DB: shyn_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    networks:
      - shyn_net

  auth-service:
    image: anarbekulym/auth-service:latest
    container_name: shyn_auth_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://shyn_postgres:5432/shyn_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres
    networks:
      - shyn_net

  nginx:
    image: nginx:latest
    container_name: shyn_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
    networks:
      - shyn_net

networks:
  shyn_net:
    driver: bridge
