spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shyn_db
    username: postgres
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: mappings