spring:
  datasource:
    # Используем переменные. Если их нет, возьмет значения после ":"
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hiking_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345678}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # ТВОИ НОВЫЕ НАСТРОЙКИ GOOGLE ТУТ
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile


# Добавляем блок Swagger/OpenAPI
springdoc:
  swagger-ui:
    # Тот самый выпадающий список сервисов
    urls:
      - name: 🔐 Auth Service
        url: /api/auth/v3/api-docs
      - name: 🏔️ Routes Service
        url: /api/routes/v3/api-docs
    # Сохраняет Bearer токен при перезагрузке страницы (мега-удобно)
    persist-authorization: true
    # Сортирует эндпоинты по алфавиту
    operations-sorter: alpha
  # Важно: чтобы Swagger правильно понимал пути через Nginx
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: mappings